# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [10]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [11]:
A = np.arange(1, 16).reshape(3,5)

In [11]:
import numpy as np

A = np.arange(1, 16).reshape(3, 5)

print("Dimensionen:", A.ndim)
print("Formen:", A.shape)
print("Storlek:", A.size)
print("Data typ:", A.dtype)


Dimensionen: 2
Formen: (3, 5)
Storlek: 15
Data typ: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

In [1]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

element_sub = B - C
print(element_sub)

element_multi = B * C
print(element_multi)

matrix_multi = B @ C
print(matrix_multi)


[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

In [30]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)
print(B)

exp_B = np.exp(B)
print(exp_B)

min_värde = np.min(B)
print(min_värde)

min_värde_rader = np.min(B, axis=1)
print(min_värde_rader)

min_värde_kolumner = np.min(B, axis=0)
print(min_värde_kolumner)

min_index = np.argmin(B)
print(min_index)

min_index_rader = np.argmin(B, axis=1)
print(min_index_rader)

summan_elements = np.sum(B)
print(summan_elements)

mean_kolumner = np.mean(B, axis=0)
print(mean_kolumner)

median_kolumner = np.median(B, axis=0)
print(median_kolumner)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print(A[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [5]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [7]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# Koden ovan visar att variabeln "a" är en dimesionell (1D) linje som visar värde från 0 till 29, däremot variabeln "b" visar att det ska vara en grupp av två som vi ser närt vi kör koden. Den visar också att varje grupp har tre rader med siffror och att den börjar från minus ett till 30.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [10]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [8]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [9]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [9]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Båda inputsen måste vara (ndarray)")
   
    if operation not in ["addera", "multiplicera"]:
        raise ValueError("Operation måste vara 'addera' eller 'multiplicera'")
   
    if operation == "addera":
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matriserna måste ha samma dimensioner för addition")
        return matrix1 + matrix2
   
    elif operation == "multiplicera":
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Antalet kolumner måste vara lika för båda matrisen")
        return np.dot(matrix1, matrix2)

A = np.array([[9, 5], [3, 2]])
B = np.array([[6, 8], [7, 1]])

print(add_mult_matrices(A, B, "addera"))

print(add_mult_matrices(A, B, "multiplicera"))

[[15 13]
 [10  3]]
[[89 77]
 [32 26]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [42]:
import numpy as np

# Uppgift 10.1.1
x = np.array([4, 3])
print(x)

# b) 5x
fem_x = 5 * x
print(f" b) 5x: {fem_x}")

# c) 3x
tre_x = 3 * x
print(f" c) 3x: {tre_x}")

# d) 5x + 3x
summan_av_fem_x_tre_x = fem_x + tre_x
print(f" d) 5x + 3x: {summan_av_fem_x_tre_x}")

# e) 8x
åtta_x = 8 * x
print(f" e) 8x: {åtta_x}")

# f) 4x - x
fyra_minus_x = 4 * x - x
print(f" f) 4x - x: {fyra_minus_x}")

# g) x trasnponering
x_transponering = x.reshape(1, -1)
print(f" g) x trasnponering: {x_transponering}")

# h) Om x + xT är definerat
definerad_x_och_xT = True
print(f" h) Är x + x^T derfinerad? {definerad_x_och_xT}")

# i) Beräkna
x_norm = np.linalg.norm(x)
print(f" i) ||x||: {x_norm}")

# Vektorn
v = np.array([3, 7, 0, 11])

# Uppgift 10.1.2 a)
dimensionen_v = v.shape[0]
print(f" a) dimensionen av v: {dimensionen_v}")

# b)
v_två = 2 * v
print(f" b) 2vektor: {v_två}")

# c) 5v + 2v
fem_plus_två_v = 5 * v + 2 * v 
print(f" c) 5v + 2v: {fem_plus_två_v}")

# d) 4v - 2v
fyra_minus_två_v = 4 * v - 2 * v
print(f" d) 4v - 2v: {fyra_minus_två_v}")

# e) Transponering av v
transponering_v = v.reshape(1, -1)
print(f" e) Transponering av Vektorn: {transponering_v}")

# f) Beräkna
v_norm = np.linalg.norm(v)
print(f" f) ||v||: {v_norm}")

# Uppgift 10.1.3 vektorerna
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# a)
v1_norm = np.linalg.norm(v1)
print(f" a) ||v1||: {v1_norm}")

# b)
v1_norm_minus_v2 = np.linalg.norm(v1 - v2)
print(f" b) ||v1 - v2||: {v1_norm_minus_v2}")

[4 3]
 b) 5x: [20 15]
 c) 3x: [12  9]
 d) 5x + 3x: [32 24]
 e) 8x: [32 24]
 f) 4x - x: [12  9]
 g) x trasnponering: [[4 3]]
 h) Är x + x^T derfinerad? True
 i) ||x||: 5.0
 a) dimensionen av v: 4
 b) 2vektor: [ 6 14  0 22]
 c) 5v + 2v: [21 49  0 77]
 d) 4v - 2v: [ 6 14  0 22]
 e) Transponering av Vektorn: [[ 3  7  0 11]]
 f) ||v||: 13.379088160259652
 a) ||v1||: 7.14142842854285
 b) ||v1 - v2||: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [28]:
import numpy as np

a = np.array([[2, 1, -1], [1, -1, 1]])
b = np.array([[4, -2, 1], [2, -4, -2]])
c = np.array([[1, 2], [2, 1]])
d = np.array([[3, 4], [4, 3]])
e = np.array([[1], [2]])
i = np.array([[1, 0], [0, 1]])

# a)
två_a = 2 * a
print(f" a) 2A: \n{två_a}\n")

# b)
b_minus_2a = b - 2 * a
print(f" b) b - 2a: \n{b_minus_2a}\n")

# c) 
tre_c_minus_två_e = 3 * c - 2 * e
print(f" c) 3c - 2e: \n{tre_c_minus_två_e}\n")

# d) 
två_d_minus_tre_c = 2  * d - 3 * c
print(f" d) 2d - 3c: \n{två_d_minus_tre_c}\n")

# e) 
d_T_add_två_d = d.T + 2 * d
print(f" e) d^T + 2d: \n{d_T_add_två_d}\n")

# f) 
två_c_T_minus_två_d_T = c.T - 2 * d.T
print(f" f) 2c^T - 2d^T: \n{två_c_T_minus_två_d_T}\n")

# g) Denna uppgift från boken är ej definerad.
a_T_min_b = a.T - b
print(f" g) aT - b: \n{a_T_min_b}\n")

# h)
try:
    ac = np.dot(a, c)
    print(f" h) ac: \n{ac}\n")
except ValueError:
    print(" h) ac är ej definerad i dimesionerna.\n")

# i)
try:
    cd = np.dot(c, d)
    print(f" i) cd: \n{cd}\n")
except ValueError:
    print(" i) cd är ej definerad i dimesionerna.\n")

# j) 
try:
    cb = np.dot(c, b)
    print(f" j) cb: \n{cb}\n")
except ValueError:
    print(" j) cb är ej definerad i dimesionerna.\n")

# k)
ci = np.dot(c, i)
print(f" k) ci: \n{ci}\n")

# l)
ab_T = np.dot(a, b.T)
print(f" l) ab^T: \n{ab_T}\n")

# Uppgift 10.2.2
matrisen_a = np.array([[2, 3, 4], [5, 4, 1]])
transponering_a = matrisen_a.T
transponering_aa = np.dot(matrisen_a, transponering_a)
print(transponering_aa)

#Uppgift 10.2.3
a_uppgift_10_2_3 = np.array([[1, 2], [2, 4]])
b_uppgift_10_2_3 = np.array([[2, 1], [1, 3]])
c_uppgift_10_2_3 = np.array([[4, 3], [0, 2]])
a_b = np.dot(a_uppgift_10_2_3, b_uppgift_10_2_3) 
a_c = np.dot(a_uppgift_10_2_3, c_uppgift_10_2_3)
lika_a_b = np.array_equal(a_b, a_c)
b_ej_lika_c = not np.array_equal(b_uppgift_10_2_3, c_uppgift_10_2_3)
print(" AB = AC:", lika_a_b)
print("B är inte lika som C", b_ej_lika_c)

 a) 2A: 
[[ 4  2 -2]
 [ 2 -2  2]]

 b) b - 2a: 
[[ 0 -4  3]
 [ 0 -2 -4]]

 c) 3c - 2e: 
[[ 1  4]
 [ 2 -1]]

 d) 2d - 3c: 
[[3 2]
 [2 3]]

 e) d^T + 2d: 
[[ 9 12]
 [12  9]]

 f) 2c^T - 2d^T: 
[[-5 -6]
 [-6 -5]]



ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

In [30]:
v1 = np.arange(4)
v2 = v1[2:]
print(v1)
print(v2)
print(v1.base)
print(v2.base)
v2[-1] = 123
print(v1)
print(v2)

[0 1 2 3]
[2 3]
None
[0 1 2 3]
[  0   1   2 123]
[  2 123]
